# Generated by Django 4.1.7 on 2023-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('num_beds', models.IntegerField()),
                ('num_baths', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
